version: "3.7"

services:

  flask:
    #Build flask container
    build: ./flask
    container_name: flask
    restart: always
    #-DB_USERNAEM=example
    environment:
      - APP_NAME=MyFlaskApp
      #expose port to internal components in a network
    expose:
      - 8080

  nginx:
    #Build nginx container
    build: ./nginx
    container_name: nginx
    restart: always
    #host:container
    ports:
      - "80:80"
